---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ sdkman_required_packages }}"
    state: latest
    update_cache: yes

- name: Install sdkman
  shell: SDKMAN_DIR="{{ user_home }}/.config/sdkman" curl -s "https://get.sdkman.io" | bash