---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ irssi_package_name }}"
    state: latest
    update_cache: yes

- name: Create irssi config file
  copy:
    dest: "{{ user_home }}/.irssi/"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: config
