 ---

- name: Ensure required packages are removed
  become: yes
  dnf:
    name: "{{ irssi_package_name }}"
    state: absent

- name: Ensure config directories are removed
  file:
    path: "{{ user_home }}/.irssi"
    state: absent
