---

- name: Ensure vscode is removed
  become: yes
  dnf:
    name: "{{ vscode_package_name }}"
    state: absent

- name: Ensure repository is removed
  file:
    path: "/etc/yum.repos.d/vscode.repo"
    state: absent