---

- name: Ensure required packages are removed
  become: yes
  dnf:
    name: "{{ bspwm_packages }}"
    state: absent

- name: Ensure config directory is removed
  file:
    path: "{{ user_home }}/.config/bspwm"
    state: absent
