---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ picom_package_name }}"
    state: latest
    update_cache: yes

- name: Create picom config file
  become: yes
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: picom
