---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ polybar_packages }}"
    state: latest
    update_cache: yes

- name: Copy config files
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    src: polybar

- name: Create polybar config file
  template:
    dest: "{{ user_home }}/.config/polybar/config.ini"
    group: "{{ user_id }}"
    owner: "{{ user_id }}"
    src: "themes/{{ theme_name }}/config.ini.j2"

- name: Create polybar scripts colors
  template:
    dest: "{{ user_home }}/.config/polybar/scripts/colors.sh"
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    src: "themes/{{ theme_name }}/colors.sh.j2"
