---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ alacritty_packages }}"
    state: latest
    update_cache: yes

- name: Create config directory
  file:
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/alacritty"
    state: directory

- name: Create alacritty config file
  template:
    dest: "{{ user_home }}/.config/alacritty/alacritty.yml"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: "alacritty.yml.j2"