---

- name: Ensure required package is removed
  become: yes
  yum:
    name: "{{ xdg_user_dirs_package_name }}"
    state: absent


- name: Ensure config file is removed
  file:
    path: "{{ user_home }}/.config/user-dirs.dirs"
    state: absent
