---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ sound_packages }}"
    state: latest
    update_cache: yes

- name: Create alsa.conf
  become: yes
  template:
    dest: "/etc/modprobe.d/alsa.conf"
    src: "alsa.conf.j2"

- name: Make sure Pipewire services are restarted
  systemd:
    name: "{{ item }}"
    scope: user
    state: restarted
  with_items:
    - pipewire
    - pipewire-pulse