---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ fonts_packages }}"
    state: latest
    update_cache: yes

- name: Create fonts directories
  become: yes
  file:
    path: "{{ fonts_directory }}/{{ item }}"
    state: directory
  with_items:
    - fontawesome
    - nerfonts

- name: Fetch Fonts Awesome latest release webpage
  uri:
    follow_redirects: "yes"
    method: GET
    return_content: yes
    url: "https://github.com/FortAwesome/Font-Awesome/releases/latest/"
  check_mode: no
  delay: 10
  register: release_webpage_raw
  retries: 30
  until: release_webpage_raw is succeeded

- name: Set Fonts Awesome download url
  check_mode: no
  set_fact:
    fontawesome_zip: "{{ release_webpage_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: '/FortAwesome/Font-Awesome/releases/download/.*fontawesome.*desktop\.zip'

- name: Ensure Fonts Awesome is downloaded
  become: yes
  unarchive:
    dest: "{{ fonts_directory }}/fontawesome"
    exclude:
      - "*/metadata/*"
      - "*/svgs/*"
    mode: 0755
    remote_src: yes
    src: "https://github.com{{ fontawesome_zip }}"

- name: Fetch Nerd Fonts latest release webpage
  uri:
    follow_redirects: "yes"
    method: GET
    return_content: yes
    url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/"
  check_mode: no
  delay: 10
  register: release_webpage_raw
  retries: 30
  until: release_webpage_raw is succeeded

- name: Set Nerd Fonts download url
  check_mode: no
  set_fact:
    nerdfonts_zip: "{{ release_webpage_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: '/ryanoasis/nerd-fonts/releases/download/.*3270\.zip'

- name: Ensure Nerd Fonts is downloaded
  become: yes
  unarchive:
    dest: "{{ fonts_directory }}/nerfonts"
    mode: 0755
    remote_src: yes
    src: "https://github.com{{ nerdfonts_zip }}"