---

- name: Ensure required packages are installed
  become: yes
  dnf:
    name: "{{ fonts_packages }}"
    state: latest
    update_cache: yes

- name: Create fonts directories
  become: yes
  file:
    path: "{{ fonts_directory }}/{{ item }}"
    state: directory
  with_items:
    - fontawesome
    - redhat

- name: Fetch Fonts Awesome latest release webpage
  uri:
    follow_redirects: "yes"
    method: GET
    return_content: yes
    url: "https://github.com/FortAwesome/Font-Awesome/releases/latest/"
  check_mode: no
  delay: 10
  register: release_webpage_raw
  retries: 30
  until: release_webpage_raw is succeeded

- name: Set Fonts Awesome download url
  check_mode: no
  set_fact:
    fontawesome_zip: "{{ release_webpage_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: '/FortAwesome/Font-Awesome/releases/download/.*fontawesome.*desktop\.zip'

- name: Ensure Fonts Awesome is downloaded
  become: yes
  unarchive:
    dest: "{{ fonts_directory }}/fontawesome"
    #include: # added in ansible 2.11
    #  - "*/otfs/*"
    exclude:
      - "*.svg"
    mode: 0755
    remote_src: yes
    src: "https://github.com{{ fontawesome_zip }}"

- name: Fetch Red Hat Fonts latest release webpage
  uri:
    follow_redirects: "yes"
    method: GET
    return_content: yes
    url: "https://github.com/RedHatOfficial/RedHatFont/releases/latest/"
  check_mode: no
  delay: 10
  register: release_webpage_raw
  retries: 30
  until: release_webpage_raw is succeeded

- name: Set Red Hat Fonts download url
  check_mode: no
  set_fact:
    redhat_zip: "{{ release_webpage_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: '/RedHatOfficial/RedHatFont/archive/refs/tags/.*\.zip'

- name: Ensure Red Hat Fonts is downloaded
  become: yes
  unarchive:
    dest: "{{ fonts_directory }}/redhat"
    #include: # added in ansible 2.11
    #  - "*/webfonts/*"
    exclude:
     - "*/webfonts/*"
    mode: 0755
    remote_src: yes
    src: "https://github.com{{ redhat_zip }}"
  